version: '3'
services:
  eureka-server:
    image: bulain/eureka-server
    restart: always
    ports:
      - 8761:8761
  eureka-service:
    image: bulain/eureka-service
    restart: always
    expose:
      - 8762
    links:
      - eureka-server
